version: '3'

services:
  # Frontend
  web:
    image: jitsi/web
    restart: always
    ports:
      - '8000:80'
      - '8443:443'
    env_file:
      - ./settings.env
    networks:
      meet.jitsi:

  # XMPP server
  prosody:
    image: jitsi/prosody
    restart: always
    expose:
      - '5222'
      - '5347'
      - '5280'
    env_file:
      - ./settings.env
    networks:
      meet.jitsi:
        aliases:
          - xmpp.meet.jitsi

  # Focus component
  jicofo:
    image: jitsi/jicofo
    restart: always
    env_file:
      - ./settings.env
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  # Video bridge
  jvb:
    image: jitsi/jvb
    restart: always
    ports:
      - '10000:10000/udp'
      - '4443:4443'
    env_file:
      - ./settings.env
    depends_on:
      - prosody
    networks:
      meet.jitsi:

# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
